models/Training.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use \yii\web\IdentityInterface;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "training".
 *
 * @property integer $id
 * @property integer $date
 * @property string $shift
 * @property integer $staff_id
 * @property integer $imp_id
 * @property integer $training_type
 * @property string $notes
 */
class Training extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'training';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['updated_by', 'updated_at', 'created_by', 'created_at', 'date', 'staff_id', 'training_type'], 'integer'],
            [['shift', 'notes'], 'string', 'max' => 255],
            [['date', 'staff_id','shift', 'training_type'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'תאריך',
            'shift' => 'משמרת',
            'staff_id' => 'איש צוות רפואי',
            'training_type' => 'סוג הדרכה',
            'notes' => 'הערות',
            'updated_by' => 'עודכן על ידי',
            'updated_at' => 'עודכן בתאריך',
            'created_by' => 'נוצר על ידי',
            'created_at' => 'נוצר בתאריך',
        ];
    }

    public function behaviors()
    {
		return 
		[
			[
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'created_by',
				'updatedByAttribute' => 'updated_by',
			 ],
				'timestamp' => [
				'class' => 'yii\behaviors\TimestampBehavior',
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
				],
			],
		];
    }

    public function getTrainingImplementor()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    public function getTrainingStaff()
    {
        return $this->hasOne(Staff::className(), ['id' => 'staff_id']);
    }

    public function getTrainingType()
    {
        return $this->hasOne(TrainingType::className(), ['id' => 'training_type']);
    }

    public function getUpdatedBy(){
        return $this->hasOne(User::className(), ['id'=>'updated_by']);
    }

    public static function findTrainFromUser($userId)
    {
        return static::find()
		->where(['created_by'=>$userId])
		->one();
    }

}

models/TrainingType.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "training_type".
 *
 * @property integer $id
 * @property string $name
 */
class TrainingType extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'training_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'סוג הדרכה',
        ];
    }

    public static function getTrainingTypes()
	{
		$trainingTypes = ArrayHelper::
					map(self::find()->all(), 'id', 'name');
		return $trainingTypes;						
	}
}

controllers/StaffController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Staff;
use app\models\StaffSearch;
use app\models\Training;
use app\models\TrainingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * StaffController implements the CRUD actions for Staff model.
 */
class StaffController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['*'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],
        ];
    }

    /**
     * Lists all Staff models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StaffSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Staff model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $searchModel = new TrainingSearch();
        $searchModel->staff_id = $this->findModel($id)->name;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('view', [
            'model' => $this->findModel($id),
            'training' => $this->findTraining($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Staff model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!\Yii::$app->user->can('createStaff')){
                throw new UnauthorizedHttpException ('אינך רשאי ליצור איש צוות'); 
            }
        $model = new Staff();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Staff model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!\Yii::$app->user->can('editStaff')){
                throw new UnauthorizedHttpException ('אינך רשאי לערוך איש צוות'); 
            }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Staff model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('deleteStaff')){
                throw new UnauthorizedHttpException ('אינך רשאי למחוק איש צוות'); 
            }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Staff model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Staff the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Staff::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findTraining($id)
    {
        if (($training = Training::find()->where(['staff_id' => $id])->one()) !== null) {
            return $training;
        } else {
            $training = 'NONE';
        }
    }
}

controllers/TrainingController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Training;
use app\models\TrainingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;
use yii\web\UnauthorizedHttpException;

/**
 * TrainingController implements the CRUD actions for Training model.
 */
class TrainingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['*'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],
        ];
    }

    /**
     * Lists all Training models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TrainingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'implementors' => User::getUsersWithTraining(),
 			'implementor' => $searchModel->created_by,
        ]);
    }

    /**
     * Displays a single Training model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Training model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!\Yii::$app->user->can('createTraining')){
                throw new UnauthorizedHttpException ('אינך רשאי ליצור הדרכות'); 
            }
        $model = new Training();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Training model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (!\Yii::$app->user->can('editTraining') && 
		    !\Yii::$app->user->can('updateOwnTraining', ['training' =>$model]) ){
			throw new UnauthorizedHttpException ('אינך רשאי לערוך הדרכות');
            }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Training model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if (!\Yii::$app->user->can('deleteTraining') && 
		    !\Yii::$app->user->can('updateOwnTraining', ['training' =>$model]) ){
			throw new UnauthorizedHttpException ('אינך רשאי למחוק הדרכות');
            }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Training model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Training the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Training::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['*'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'roles' => User::getRoleWithAllRoles(),
			'role' => $searchModel->role,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
 		//access control
		if (!\Yii::$app->user->can('createUser')){
            throw new UnauthorizedHttpException ('אינך רשאי ליצור משתמשים');
        }		
		$model = new User();
		
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
			$roles = User::getRoles(); 
            return $this->render('create', [
                'model' => $model,
				'roles' => $roles,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
  public function actionUpdate($id)
    {
		$model = $this->findModel($id);
		if (!\Yii::$app->user->can('updateUser') && 
		    !\Yii::$app->user->can('updateOwnUser', ['user' =>$model]) ){
			throw new UnauthorizedHttpException ('אינך רשאי לערוך משתמשים');
            }
			
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
			$roles = User::getRoles(); 
			return $this->render('update', [
				'model' => $model,
				'roles' => $roles,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('deleteUser')){
                throw new UnauthorizedHttpException ('אינך ראשי למחוק משתמשים'); 
            }
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
			$roles = \Yii::$app->authManager->getRolesByUser($model->id);
			$model->role = array_keys($roles)[0];
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/training/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;
use kartik\datetime\DateTimePicker;
use app\models\Status;
use app\models\User;
use app\models\Issue;
use app\models\TrainingType;
use app\models\Department;
use app\models\Staff;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Training */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="training-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'date')->widget(DateControl::classname(), [
                        'type'=>DateControl::FORMAT_DATE,
                        'ajaxConversion'=>true,
                        'saveFormat' => 'php:U',
                        'options' => [
                            'pluginOptions' => [
                                'autoclose' => true
                            ]
                        ]
                    ]);
                ?>

    <?=$form->field($model, 'shift')->widget(Select2::classname(), [
                    'data' => Issue::getShifts(),
                    'options' => ['placeholder' => 'בחר משמרת'],
                    'language' => 'he',
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
    ?>

    <?=$form->field($model, 'staff_id')->widget(Select2::classname(), [
                        'data' => Staff::getStaffMembers(),
                        'options' => ['placeholder' => 'בחר איש צוות'],
                        'language' => 'he',
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]);
    ?>

    

    <?=$form->field($model, 'training_type')->widget(Select2::classname(), [
                        'data' => TrainingType::getTrainingTypes(),
                        'options' => ['placeholder' => 'בחר סוג הדרכה'],
                        'language' => 'he',
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]);
    ?>

    <?= $form->field($model, 'notes')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'צור הדרכה' : 'עדכן', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/training/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TrainingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="training-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'shift') ?>

    <?= $form->field($model, 'staff_id') ?>

    <?= $form->field($model, 'imp_id') ?>

    <?php // echo $form->field($model, 'training_type') ?>

    <?php // echo $form->field($model, 'notes') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/training/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Training */

$this->title = 'הדרכה חדשה';
$this->params['breadcrumbs'][] = ['label' => 'הדרכות', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="training-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/training/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\datecontrol\DateControl;
use kartik\daterange\DateRangePicker;
use kartik\export\ExportMenu;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TrainingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'הדרכות';
$this->params['breadcrumbs'][] = $this->title;
$gridColumns = [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'date',
                'value' => function($model){return date('d/m/Y', $model->date);},
				'label' => 'תאריך',
				'format' => 'raw',
                'filter' => DateRangePicker::widget([
                    'name'=>'date_range',
                    'presetDropdown'=>true,
                    'hideInput'=>true,
                    //'convertFormat'=>true,
                    'pluginOptions' => [
                        'locale'=>[
                            'separator'=>'to',
                        ],
                        'opens'=>'left',
                    ]
                    
                ])
            ],
            'shift',
            [
				'attribute' => 'created_by',
				'label' => 'שם המטמיע',
				'format' => 'raw',
				'value' => function($model){return Html::a($model->trainingImplementor->name, ['user/view', 'id' => $model->trainingImplementor->id]);
				},
                'filter'=>Html::dropDownList('TrainingSearch[created_by]', $implementor, $implementors, ['class'=>'form-control']),
			],
            [
				'attribute' => 'staff_id',
				'label' => 'שם איש הצוות',
				'format' => 'raw',
				'value' => function($model){return Html::a($model->trainingStaff->name, ['staff/view', 'id' => $model->trainingStaff->id]);
				},
			],
            [
				'attribute' => 'training_type',
				'label' => 'סוג הדרכה',
				'format' => 'raw',
				'value' => function($model){
					return $model->trainingType->name;
				},
			],
            ['attribute' => 'notes',
        'format' => 'ntext'],

            ['class' => 'yii\grid\ActionColumn'],
        ];
?>
<div class="training-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
         <p>
        <?= Html::a('הדרכה חדשה', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    </div>
    <div class="pull-left">
    <?php
    echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'exportConfig' => [
        'PDF' => false,
        'HTML' => false,
        'CSV' => false,
    ],
    'fontAwesome' => true,
    'dropdownOptions' => [
        'label' => 'ייצא נתונים',
        'class' => 'btn btn-default'
    ]
    ]);
    //echo "<hr>\n";

    ?>
    </div>
</div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumns,
        'pager' => [
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'],
    ]); ?>
</div>

views/training/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Training */

$this->title = 'עדכון פרטי הדרכה - ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'הדרכות', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'הדרכה מספר - ' . $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'עדכון';
?>
<div class="training-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/training/view.php
<?php

use yii\helpers\Html;
// use yii\widgets\DetailView;
use kartik\detail\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Training */

$this->title = "הדרכה מספר  " . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'הדרכות', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="training-view">

    

    <p>
        <?= Html::a('עדכון', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('מחיקה', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'למחוק את ההדרכה?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'condensed'=>false,
        'enableEditMode' => false,
        'hover'=>true,
        'mode'=>DetailView::MODE_VIEW,
        'panel'=>[
        'heading'=>'<h2>' . $this->title . '</h2>',
        'type'=>DetailView::TYPE_INFO,
        ],
        'attributes' => [
            [
            'group'=>true,
            'label'=>'פרטי ההדרכה',
            'rowOptions'=>['class'=>'success']
            ],
            ['columns' => [
                        [
                        //Date of training
                            'label' => $model->attributeLabels()['date'],
                            'value' => date('d/m/Y', $model->date),
                            'valueColOptions'=>['class'=>'col-md-2'],
                        ],
                        ['attribute'=> 'shift',
                        'valueColOptions'=>['class'=>'col-md-2']],

                        [ // Who Created the training
                            'label' => $model->attributeLabels()['created_by'],
                            'format' => 'html',
                            'valueColOptions'=>['class'=>'col-md-3'],
                            'value' => is_object($model->trainingImplementor) ? (Html::a($model->trainingImplementor->name, ['user/view', 'id' => $model->trainingImplementor->id])) : "לא הוגדר",
                            ],
                        ]
            ],
            ['columns' => [
                        ['attribute'=> 'staff_id',
                        'format' => 'html',
                        'value' => is_object($model->trainingStaff) ? (Html::a($model->trainingStaff->name, ['staff/view', 'id' => $model->trainingStaff->id])) : "לא הוגדר",
                        'valueColOptions'=>['class'=>'col-md-2']],
                        [ 
                        'label' => $model->attributeLabels()['training_type'],
                        'value' => $model->trainingType->name,
                        'valueColOptions'=>['class'=>'col-md-6']],          
            ]
            ],
            ['attribute' => 'notes',
            'format' => 'ntext'],
            [
            'group'=>true,
            'label'=>'פרטי עדכון',
            'rowOptions'=>['class'=>'success']
        ],
        ['columns' => [
            [ // Who updated the issue
                            'label' => $model->attributeLabels()['updated_by'],
                            'format' => 'html',
                            'valueColOptions'=>['class'=>'col-md-3'],
                            'value' => 
                                is_object($model->updatedBy) ? (Html::a($model->updatedBy->name, ['user/view', 'id' => $model->updatedBy->id])) : "לא עודכן",
            ],
            [
            //Date of update
                            'label' => $model->attributeLabels()['updated_at'],
                            'value' => ($model->updated_at == NULL) ? "לא עודכן" : date('d/m/Y', $model->updated_at),
                            'valueColOptions'=>['class'=>'col-md-2'],
            ],
            ]
        ], 
        ],
    ]) ?>

</div>